### ISSUE TITLE
Pre-trained ember model?

### ISSUE THREAD

**Issue by Ybakman** [whyisyoung/BODMAS#1]
Thanks for your sharing the code! I couldn't find the pre-trained ember model. There is a print statement in concept_drift_ember.py : {fixed_model_path} not exist, need to execute "run_contro.sh" with ember as the training set first.
 But I couldn't find run_contro.sh . Is there any google drive link for pretrained ember GBT model?
Thanks

**Comment by whyisyoung** [comment]
thanks for catching that! Could you read the examples section in README and try ./main_pretrain.sh to generate the pre-trained model for ember?

**Comment by Ybakman** [comment]
Thanks for the answer
