### ISSUE TITLE
Concept Drift Experiments with CADE

### ISSUE THREAD

**Issue by Ybakman** [whyisyoung/BODMAS#2]
Did you have a chance to do concept drift experiments with CADE? This is also your paper and the idea is great. I wonder how it performs on BODMAS dataset.
Thanks for your helping

**Comment by whyisyoung** [comment]
Hi, we did try CADE on part of the BODMAS dataset when CADE was written. 
But after that we have several projects ongoing and we haven't explore further.
You can have a try : )
