### ISSUE TITLE
Unknown Malware Families 

### ISSUE THREAD

**Issue by Ybakman** [whyisyoung/BODMAS#3]
Hi,
When I examine the families of the malware in the data, I saw there are 582 different labels. However, 2 of them are "Unknown" and "unknown" (Capital case differs). So, it makes 580 families in total but the paper says there are 581 families. Am I missing sth? 
Thanks for your help!

**Comment by whyisyoung** [comment]
Thanks for catching this. The total number of families should be 580. 
There are a few samples (see the table below) with a family called "Unknown" or "unknown". I filtered them out but forgot to do the lowercase again. 
So after removing these names, it should be 580 in total. 


sha | timestamp | family
-- | -- | --
839a04b1ca0b731e0e58daab3598ced6ec12c10572861ce318fba9eea623f4ec | 2019-09-03 00:01:12+00:00 | Unknown
a726b564bf8d7f1653dcbde5154d5b24b4d8076dedf7b2d72c710a9cc42d837d | 2019-09-20 09:51:00+00:00 | Unknown
90e55e728f54b4d9e812f5ea138af09e98bd470982abbad95329518aaa456f9a | 2019-10-02 11:36:06+00:00 | Unknown
0a507384c23cdd43ddac83bc275656c3771636b3b525ec1b75e8b5e666ed69da | 2019-12-01 00:00:00+00:00 | unknown
2648509a359d0b5a2975bae854f3170766f87f04fcd160ebe280f8d1d7c375ef | 2019-12-01 00:00:00+00:00 | unknown
811e1bc64684a8f7676a6f808e499107f54bb0826d160eff9ff0efe42370703d | 2020-06-17 05:59:55+00:00 | Unknown
da7d64dbf3b949913b59b029670d454cea0e5efa343c9888f823224b4c513e84 | 2020-06-25 15:41:26+00:00 | Unknown
